spring:
  application:
    name: course-catalog-service
  datasource:
    url: jdbc:postgresql://localhost:5432/courses
    username: postgres
    password: 112358
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  h2:
    console:
      enabled: true
message: Hello from default profile